-- SQL Dump Import Data Awal untuk Database MySQL (nfi_production_db)
-- PT Nusantara Film Indonesia

USE `nfi_production_db`;

-- 1. Users Admin
TRUNCATE TABLE `users`;
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `created_at`, `updated_at`) VALUES
(1, 'Administrator Utama', 'admin@nfi.co.id', NOW(), '$2y$12$6/m2jLqN.kE8b2y0Nq3qceQ6L6PZ1.d/0fXhF1G9y5OaR5j6b7C2e', NOW(), NOW()),
(2, 'Redaksi News & Editor', 'editor@nfi.co.id', NOW(), '$2y$12$6/m2jLqN.kE8b2y0Nq3qceQ6L6PZ1.d/0fXhF1G9y5OaR5j6b7C2e', NOW(), NOW()),
(3, 'Legal Auditor', 'legal@nfi.co.id', NOW(), '$2y$12$6/m2jLqN.kE8b2y0Nq3qceQ6L6PZ1.d/0fXhF1G9y5OaR5j6b7C2e', NOW(), NOW());

-- 2. Portfolios
TRUNCATE TABLE `portfolios`;
INSERT INTO `portfolios` (`id`, `uuid`, `title`, `slug`, `category`, `client`, `year`, `thumbnail`, `video_url`, `synopsis`, `credits`, `awards`, `featured`, `status`, `created_at`, `updated_at`) VALUES
(1, '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0001', 'Ken Arok: Rahasia Takdir Tumapel', 'ken-arok-rahasia-takdir-tumapel', 'Film', 'GH Production / PT. Nusantara Film Indonesia', 2002, 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=1200', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Ken Arok lahir dari Ken Endok dan dibesarkan di lingkungan keras. Pengalaman melihat penderitaan rakyat miskin membuka hatinya untuk membela mereka. Pertemuannya dengan Ken Dedes dan intrik Mpu Gandring mengubah peta sejarah kerajaan Tumapel secara abadi.', '{"director":"SA. Karim & George Rudy","cast":["George Rudy","Donny Kesuma","Christy Jusung","Jack Rio Altriara"]}', '["Pemenang Nominasi Sinematografi Terbaik 2002"]', 1, 'Published', '2024-01-15 10:00:00', '2024-01-15 10:00:00'),
(2, '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0002', 'Anie Carera - Walau Seribu Tahun', 'anie-carera-walau-seribu-tahun', 'Musik', 'GH Record / NFI Music', 1989, 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=1200', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Album legendaris kedua dari legenda musik pop Indonesia Anie Carera, diproduksi di bawah naungan GH Record (cikal bakal NFI Music). Memperoleh penghargaan musik nasional.', '{"director":"George Handiwiyanto","cast":["Anie Carera","Areng Widodo (Music Arranger)"]}', '["Album Pop Terbaik 1989"]', 1, 'Published', '2024-01-20 10:00:00', '2024-01-20 10:00:00'),
(3, '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0003', 'Suraya Rock Star 1988 & Surabaya Rock Band "Teror"', 'suraya-rock-star-1988-teror', 'Musik', 'GH Enterprise & PT. Gudang Garam Kediri', 1988, 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1200', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Konser kolosal dan perhelatan panggung musik rock terbesar Jawa Timur era 1988 menampilkan SAS, Sonatha Tanjung, Arthur Kaunang, Syech Abidin, dan AKA Harahap.', '{"director":"GH Enterprise SBY","cast":["Surabaya Rock Band (SRB)","Thomas","Gatuk Gondez","Mustich BK","Gita Nikki"]}', NULL, 1, 'Published', '2024-02-01 10:00:00', '2024-02-01 10:00:00'),
(4, '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0004', 'Iklan Komersial Bank Nusantara 2025', 'iklan-komersial-bank-nusantara-2025', 'Iklan', 'Bank Nusantara', 2025, 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=1200', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Video komersial resolusi 4K Anamorphic untuk penayangan TV nasional dan kampanye digital media sosial dengan tema Kemudahan Transaksi Digital.', '{"director":"Dimas Arya","cast":["Reza Rahadian","Tara Basro"]}', '["TVC Terfavorit 2025"]', 1, 'Published', '2025-01-10 10:00:00', '2025-01-10 10:00:00'),
(5, '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0005', 'Company Profile Trans-Java Megaproject', 'company-profile-trans-java-megaproject', 'Video Korporat', 'Kementerian PUPR & BUMN Konsorsium', 2024, 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&q=80&w=1200', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Video korporat eksklusif pemetaan infrastruktur dengan pengambilan gambar udara (drone FPV & Heavy Lift Cinema Rig) serta grafis gerak (motion graphics 3D).', '{"director":"Budi Santoso","cast":["Narrator: Ario Bayu"]}', NULL, 1, 'Published', '2024-11-20 10:00:00', '2024-11-20 10:00:00');

-- 3. News Posts
TRUNCATE TABLE `news_posts`;
INSERT INTO `news_posts` (`id`, `uuid`, `title`, `slug`, `category`, `author`, `featured_image`, `excerpt`, `content`, `tags`, `seo_title`, `seo_description`, `published_at`, `created_at`, `updated_at`) VALUES
(1, 'n1-uuid-001', 'PT. Nusantara Film Indonesia Raih Penghargaan Sinematografi Terbaik 2025', 'pt-nusantara-film-indonesia-raih-penghargaan-sinematografi-terbaik-2025', 'Penghargaan', 'Redaksi NFI', 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1200', 'PT. Nusantara Film Indonesia kembali mengharumkan nama bangsa di ajang perfilman regional melalui pencapaian sinematografi dan tata cahaya terbaik.', '<p>PT. Nusantara Film Indonesia resmi menerima tropi Penghargaan Sinematografi Terbaik dalam festival karya visual tahunan yang diselenggarakan di Jakarta.</p>', '["Cinema","Awards","Nusantara Film","Karya Anak Bangsa"]', 'PT Nusantara Film Indonesia Raih Penghargaan Sinematografi Terbaik', 'Berita resmi PT Nusantara Film Indonesia memenangkan penghargaan sinematografi terbaik di festival film nasional.', '2025-06-12 09:00:00', NOW(), NOW()),
(2, 'n2-uuid-002', 'Tren Video Marketing 2026: Dominasi Sinematik & Storytelling Emosional', 'tren-video-marketing-2026-dominasi-sinematik-storytelling-emosional', 'Edukasi', 'Budi Santoso', 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=1200', 'Pelajari bagaimana pendekatan penceritaan berbasis film bioskop kini menjadi strategi utama brand-brand besar dalam menarik simpati konsumen.', '<p>Perkembangan teknologi konsumen mengubah cara publik menikmati iklan komersial. Iklan yang berdurasi singkat namun mengusung alur cerita dramatis terbukti memiliki angka engagement tinggi.</p>', '["Video Marketing","Commercial","Branding","Tips Film"]', 'Tren Video Marketing 2026 - Analisis PT Nusantara Film Indonesia', 'Panduan lengkap tren video komersial dan sinematik marketing tahun 2026 dari praktisi industri film.', '2025-05-20 10:30:00', NOW(), NOW()),
(3, 'n3-uuid-003', 'Pentingnya Payung Hukum & Lisensi Dalam Industri Kreatif Sinema', 'pentingnya-payung-hukum-lisensi-dalam-industri-kreatif-sinema', 'Hukum & HKI', 'Billy Handiwiyanto, S.H., M.H.', 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=1200', 'Sinergi NFI dan Handiwiyanto Law Office dalam memberikan kepastian hukum bagi setiap aset video, musik, dan kontrak sutradara.', '<p>Banyak produser independen menghadapi kendala distribusi akibat lemahnya perlindungan hak cipta dan draf perjanjian lisensi.</p>', '["Legal","HKI","Hak Cipta","Firma Hukum"]', 'Perlindungan Hukum & Hak Cipta Sinema - NFI & Handiwiyanto Law Office', 'Edukasi pentingnya perlindungan hak kekayaan intelektual (HKI) dalam industri film Indonesia.', '2025-04-10 14:15:00', NOW(), NOW());

-- 4. Services
TRUNCATE TABLE `services`;
INSERT INTO `services` (`id`, `slug`, `title`, `short_description`, `full_description`, `deliverables`, `sample_image`, `icon`, `created_at`, `updated_at`) VALUES
(1, 'produksi-film-sinema', 'Produksi Film & Sinema', 'Layanan produksi film pendek, feature film layar lebar, dokumenter, serta sinema elektronik dengan standar internasional.', 'PT. Nusantara Film Indonesia menyediakan ekosistem pembuatan film secara utuh (End-to-End Film Production). Mulai dari pengembangan skenario, casting sutradara & pemain, lokasi syuting, kru teknis berlisensi, peralatan kamera bioskop RED/ARRI, hingga post-production.', '["Master Film DCP (Digital Cinema Package) 4K","Sound Mixing 5.1 & Dolby Atmos","Trailers, Teaser & Marketing Asset Kit","Registrasi Lisensi & Hak Cipta HKI"]', 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1200', 'Clapperboard', NOW(), NOW()),
(2, 'iklan-komersial-video', 'Iklan & Komersial Video', 'Pembuatan video iklan komersial untuk penayangan Televisi (TVC), Digital Platform, YouTube Ads, & Social Media Viral.', 'Kami membantu brand Anda menyampaikan pesan secara berdampak tinggi. Didukung tim kreatif, sutradara komersial berpengalaman, dan peralatan pencahayaan kelas atas.', '["TV Commercial 30s & 15s Cutdown","Vertical Video Aspect 9:16 (TikTok/Reels)","Color Graded Master Files 1080p / 4K"]', 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=1200', 'Tv', NOW(), NOW()),
(3, 'video-korporat-profile', 'Video Korporat & Profile', 'Video company profile, pelaporan kinerja tahunan, event liputan eksekutif, dan presentasi investor berkelas.', 'Representasikan profesionalisme perusahaan Anda di mata publik, klien, dan investor dengan video profil korporat yang sinematik.', '["Full Company Profile Video (3-5 menit)","Executive Interview Sessions","Aerial Infrastructure & Factory Drone Footage"]', 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&q=80&w=1200', 'Building2', NOW(), NOW()),
(4, 'promotor-musik-konser', 'Promotor Musik & Konser', 'Penyelenggaraan konser musik nasional & mancanegara, festival seni budaya, serta acara hiburan berskala besar.', 'Bermula dari pengalaman GH Enterprise menggelar Surya Rock Star 1988, kami berpengalaman dalam menangani izin kepolisian, tata panggung lighting sound system megah, dan penanganan artis kelas dunia.', '["Event Management & Stage Operations","Sound System & Multi-Angle Live Camera Broadcast","Perizinan Tempat & Legalitas Keramaian"]', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1200', 'Music', NOW(), NOW()),
(5, 'firma-hukum-advokasi-media', 'Firma Hukum & Advokasi Media', 'Perlindungan payung hukum karya sinema, lisensi hak cipta, kontrak artis, serta advokasi legal media oleh Handiwiyanto Law Office.', 'Satu-satunya rumah produksi terpadu di Indonesia yang didukung penuh oleh Firma Hukum Top 10 Indonesia (Handiwiyanto Law Office).', '["Penyusunan Kontrak Kerja & Talent Agreement","Pendaftaran Hak Cipta & Merek Dagang","Legal Clearance Dokumen Penayangan Sinema"]', 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=1200', 'Scale', NOW(), NOW());

-- 5. Team Members
TRUNCATE TABLE `team_members`;
INSERT INTO `team_members` (`id`, `uuid`, `name`, `position`, `department`, `biography`, `photo`, `order`, `socials`, `created_at`, `updated_at`) VALUES
(1, 't1-uuid-001', 'Billy Handiwiyanto, S.H., M.H.', 'Direktur Utama & Penasihat Hukum', 'Direksi & Legal', 'Billy Handiwiyanto merupakan pimpinan PT. Nusantara Film Indonesia sekaligus advokat senior dari Handiwiyanto Law Office (Top 10 Litigation Law Firm Indonesia).', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=600', 1, '{"email":"billy@nfi.co.id","linkedin":"https://linkedin.com"}', NOW(), NOW()),
(2, 't2-uuid-002', 'Andi Pratama', 'Direktur Operasional Production', 'Produksi', 'Pengalaman lebih dari 15 tahun mengelola manajemen lokasi syuting, kru teknis, serta pengadaan armada peralatan sinematografi.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600', 2, '{"email":"andi@nfi.co.id"}', NOW(), NOW()),
(3, 't3-uuid-003', 'Rina Kartika', 'Produser Eksekutif', 'Produksi', 'Produser kawakan yang menangani perencanaan alokasi anggaran, jalinan sponsor, dan distribusi internasional film dokumenter.', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600', 3, '{"email":"rina@nfi.co.id"}', NOW(), NOW()),
(4, 't4-uuid-004', 'Dimas Arya', 'Sutradara / Head Director', 'Kreatif & Sutradara', 'Sutradara muda berbakat peraih berbagai festival sinematografi dengan spesialisasi pencahayaan dramatis.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600', 4, '{"email":"dimas@nfi.co.id"}', NOW(), NOW());
